In [1]:
import numpy as np

In [37]:
a = np.array([1,2,3], dtype='int8')
print (a)

[1 2 3]


In [14]:
 b = np.array([2,3,4])
print (b)

[2 3 4]


In [18]:
c= np.array([[1.2,1.3,1.4,1.5,1.6],[2.1,2.2,2.3,2.4,2.5],[3.2,3.3,3.4,3.5,3.6],[4.1,4.2,4.3,4.4,4.5]])
print (c)

[[1.2 1.3 1.4 1.5 1.6]
 [2.1 2.2 2.3 2.4 2.5]
 [3.2 3.3 3.4 3.5 3.6]
 [4.1 4.2 4.3 4.4 4.5]]


In [19]:
b.ndim

1

In [20]:
c.ndim

2

In [21]:
a.shape

(3,)

In [22]:
c.shape

(4, 5)

In [24]:
a.dtype

dtype('int32')

In [34]:
a.itemsize

2

In [36]:
a.itemsize

4

In [38]:
a.itemsize

1

In [39]:
a.itemsize * a.size

3

In [40]:
a.nbytes

3

In [41]:
a.size

3

In [42]:
b.size

3

In [43]:
c.nbytes

160

In [44]:
c.size

20

In [46]:
c.itemsize

8